### ISSUE TITLE
Add option to keep certain tabs loaded

### ISSUE THREAD

**Issue by robbely** [igorlogius/limit-active-tabs#1]
Would it be possible to add the option (eg right click menu on tab) to keep certain tabs active?
There are several addons that do this, and several (such as this one) that allow you to keep the most recent tabs active, but no addons that do both since the old xul addon "Auto Unload Tab"

**Comment by igorlogius** [comment]
This feature kind of already exists :-) 
You can just pin a tab and it will automatically be excluded from unloading.
And it is also at a glance noticable which tabs are unloadable and which arent. 

If i add an option to not unload normal tabs i dont see a good way to make them visible at a glance.

**Comment by robbely** [comment]
Many thanks for your reply. Unfortunately it wouldn't cover my use case. I generally leave most or all of my pinned tabs unloaded (I hadn't realized your extension won't unload these). There are frequent situations where I need some normal tabs to remain loaded, but have no more than 10 other tabs loaded.

This was all catered for in the "Auto Unload Tab" add-on, it is unfortunate that no-one has created a replacement with all of its features.  I'm not sure if that add-on's source code is still available and could be used in part.

**Comment by igorlogius** [comment]
I'll see what i can do.

**Comment by igorlogius** [comment]
i havent taken a look at this addon for a while, so excuse my incorrect inital advie ... but from what i see you can just click the toolbar button/icon to exclude any normal tab from unloading.

I'll update the addon to show the toolbar icon per default. 
Seems like it currenlty is hidden out of the box.

**Comment by robbely** [comment]
That would be great if it can do that. Would it be possible to include pinned tabs in the unloading process (either as an option or alt version for github)?

**Comment by igorlogius** [comment]
> Would it be possible to include pinned tabs in the unloading process (either as an option or alt version for github)?

I dont see any technical issue with adding an option but the request does sound a little strange to me since i maybe incorrectly assume that pinned tabs already have a "higher priority" and unloading them doesnt seem to be something one would generally want. 
Unless maybe if hardware resources are very very limited.

**Comment by robbely** [comment]
Yes I'm guessing my workflow is different to yours. I use pinned tabs for easy access but don't need regular checking, eg some emails, parcel tracking and websites with points collecting. I can use the exclude option for any pins i want to be left active.

**Comment by igorlogius** [comment]
Added the options. 
Hope it improves your workflow.

**Comment by robbely** [comment]
Many thanks :) that's great
